- name: create aws and r53 records
  hosts: localhost
  vars:
   zone: sukeshdaws.shop
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     instance_type: t2.micro
     name: "{{ item }}"
     security_group: allow-everything
     image_id: ami-09c813fb71547fc4f
     tags:
      Name: "{{ item }}"
    loop:
    - db
    - frontend
    - backend
    register: ec2_instance_info 

  - name: print output
    ansible.builtin.debug:
     msg: "output: {{ ec2_instance_info }}"



  # - name: create r53 records
  #   amazon.aws.route53:
  #   record
