- name: install nginx
  become: yes
  hosts: frontend
  tasks:
  - name: install Nginx
    ansible.builtin.dnf:  dnf install nginx -y

  - name: enable nginx
    ansible.builtin.service: enable the service

  - name:  start the service
    ansible.builtin.service:
     name: start nginx
     state: started    
  

